### ISSUE TITLE
No API, requires scraping.

### ISSUE THREAD

**Issue by genio** [p5-shorten/www-shorten-0rz#1]
Should we consider deprecation rather than continue down this type of line?

``` perl
package WWW::Shorten::0rz;
use strict;
use warnings;
use Carp ();
use Mojo::DOM58;
use WWW::Mechanize;

use base qw( WWW::Shorten::generic Exporter );
our @EXPORT = qw( makeashorterlink makealongerlink );

our $VERSION = '0.071';
$VERSION = eval $VERSION;

sub makeashorterlink {
    my $url = shift or Carp::croak("A URL is required.");
    my $mech = WWW::Mechanize->new;
    $mech->add_header('Accept' => 'text/html');
    $mech->get('http://0rz.tw/create');
    $mech->submit_form(
        form_id     => 'redirect-form',
        fields      => { url => $url, },
    );
    return undef unless $mech->response->is_success;
    my $dom = Mojo::DOM58->new($mech->response->decoded_content);
    return $dom->find('div#doneurl > a')->last->attr('href');
}

1;
```

Having to use WWW::Mechanize is already one strike in my opinion.  But, having to scrape the results like this is borderline deprecate worthy.

**Comment by gugod** [comment]
I don't see why scraping should imply deprecation, but I also don't see why it should be kept maintained indefinitely.

I guess I'll still vote for deprecation since it is just a larger burden comparing to other alternatives.

**Comment by genio** [comment]
It's bad because it relies on them not changing their markup.  There is no `id` or `name` attribute for the `<a>` tag that we're pulling the URL from.  We're relying on it being in a `<div>` that's placed somewhere on the page and that the `<a>` we want will be the last one within that `<div>`.

Not only would we have to keep up with any changes they make for the form since it's not an API and they do the redirect madness if you don't `POST` the data with `WWW::Mechanize` keeping the session, but we then have to rely on their markup design.

As the module's currently broken, I guess we should fix it and publish it out even though we're scraping, but this will require lots of effort to stay on top of.
